package hierkeys

import (
	"fmt"

	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	"github.com/tuneinsight/lattigo/v6/ring"
)

// TransmissionKeys holds everything the client sends to the server.
// This is the only data that crosses the client-server boundary.
type TransmissionKeys struct {
	// HomingKey switches from s̃₁ to s in R (at HK parameter level).
	HomingKey *rlwe.EvaluationKey

	// MasterRotKeys are GaloisKeys in R' at RPrimeMaster level (degree 2N),
	// paper convention: each encrypts P_hk·G_i·π(s̃) under s̃.
	// Indexed by rotation index (not Galois element).
	MasterRotKeys map[int]*rlwe.GaloisKey

	// Shift0Key is the identity (shift-0) GaloisKey at RPrime level (degree 2N).
	// It encrypts P_eval·s̃ under s̃ and serves as the seed for RotToRot.
	Shift0Key *rlwe.GaloisKey
}

// KeyGenerator generates transmission keys on the client side.
// It does NOT store the secret key — following lattigo's KeyGenerator pattern.
type KeyGenerator struct {
	params       Parameters
	kgenHK       *rlwe.KeyGenerator // at HK parameter level
	kgenRP       *rlwe.KeyGenerator // at R' level-0 parameter level
	kgenRPMaster *rlwe.KeyGenerator // at R' master parameter level
}

// NewKeyGenerator creates a KeyGenerator for the given hierarchical parameters.
func NewKeyGenerator(params Parameters) *KeyGenerator {
	return &KeyGenerator{
		params:       params,
		kgenHK:       rlwe.NewKeyGenerator(params.HK),
		kgenRP:       rlwe.NewKeyGenerator(params.RPrime),
		kgenRPMaster: rlwe.NewKeyGenerator(params.RPrimeMaster),
	}
}

// GenSecretKeyNew generates a secret key at the homing-key level.
// The returned key has Q = Q_eval ∪ P_eval and P = P_hk.
//
// For evaluation (encryption/decryption), project it to eval level with
// [ProjectToEvalKey].
func (kgen *KeyGenerator) GenSecretKeyNew() *rlwe.SecretKey {
	return kgen.kgenHK.GenSecretKeyNew()
}

// ProjectToEvalKey projects a homing-key-level secret key to evaluation level.
// The evaluation key has Q = Q_eval and P = P_eval.
//
// This copies the first QCount primes to Q and remaps the remaining primes to P.
func (kgen *KeyGenerator) ProjectToEvalKey(skHK *rlwe.SecretKey) *rlwe.SecretKey {
	skEval := rlwe.NewSecretKey(kgen.params.Eval)
	for m := 0; m <= kgen.params.Eval.MaxLevel(); m++ {
		copy(skEval.Value.Q.Coeffs[m], skHK.Value.Q.Coeffs[m])
	}
	for m := 0; m <= kgen.params.Eval.MaxLevelP(); m++ {
		copy(skEval.Value.P.Coeffs[m], skHK.Value.Q.Coeffs[kgen.params.Eval.QCount()+m])
	}
	return skEval
}

// GenTransmissionKeys generates a homing key and master rotation keys.
//
// The sk must be generated by [GenSecretKeyNew] (at HK level).
// masterRotations specifies which rotation indices to generate master keys for.
// Use [MasterRotationsForBase] to compute a good set.
//
// The returned TransmissionKeys is sent to the server.
func (kgen *KeyGenerator) GenTransmissionKeys(sk *rlwe.SecretKey, masterRotations []int) (*TransmissionKeys, error) {

	if sk == nil {
		return nil, fmt.Errorf("secret key must not be nil")
	}

	// Generate s̃₁ (independent secret in R at HK level)
	skS1 := kgen.kgenHK.GenSecretKeyNew()

	// Homing key: switches s̃₁ → s at HK level
	homingKey := kgen.kgenHK.GenEvaluationKeyNew(skS1, sk)

	// Construct s̃ at both R' levels
	skTildeLow := kgen.constructExtendedSKForParams(kgen.params.RPrime, sk, skS1)
	skTildeHigh := kgen.constructExtendedSKForParams(kgen.params.RPrimeMaster, sk, skS1)

	// Generate shift-0 key at RPrime (level-0 seed for RotToRot)
	// Paper convention: genEvalKey(skIn=s̃, skOut=s̃) — identity rotation
	shift0EK := kgen.kgenRP.GenEvaluationKeyNew(skTildeLow, skTildeLow)
	shift0Key := &rlwe.GaloisKey{
		EvaluationKey: *shift0EK,
		GaloisElement: 1, // identity
		NthRoot:       kgen.params.RPrime.RingQ().NthRoot(),
	}

	// Generate master rotation keys at RPrimeMaster level (paper convention)
	masterRotKeys := make(map[int]*rlwe.GaloisKey, len(masterRotations))
	for _, rot := range masterRotations {
		galElRP := kgen.params.RPrimeMaster.GaloisElement(rot)

		// Paper convention: genEvalKey(skIn=π(s̃), skOut=s̃)
		skTildeAut := rlwe.NewSecretKey(kgen.params.RPrimeMaster)
		index, err := ring.AutomorphismNTTIndex(kgen.params.RPrimeMaster.N(), kgen.params.RPrimeMaster.RingQ().NthRoot(), galElRP)
		if err != nil {
			return nil, fmt.Errorf("AutomorphismNTTIndex for rot=%d: %w", rot, err)
		}
		kgen.params.RPrimeMaster.RingQ().AutomorphismNTTWithIndex(skTildeHigh.Value.Q, index, skTildeAut.Value.Q)
		kgen.params.RPrimeMaster.RingP().AutomorphismNTTWithIndex(skTildeHigh.Value.P, index, skTildeAut.Value.P)

		evk := kgen.kgenRPMaster.GenEvaluationKeyNew(skTildeAut, skTildeHigh)
		masterRotKeys[rot] = &rlwe.GaloisKey{
			EvaluationKey: *evk,
			GaloisElement: galElRP,
			NthRoot:       kgen.params.RPrimeMaster.RingQ().NthRoot(),
		}
	}

	return &TransmissionKeys{
		HomingKey:     homingKey,
		MasterRotKeys: masterRotKeys,
		Shift0Key:     shift0Key,
	}, nil
}

// constructExtendedSKForParams builds s̃ = s + Y·s̃₁ in R' for the given R' parameter set.
func (kgen *KeyGenerator) constructExtendedSKForParams(paramsRP rlwe.Parameters, skS, skS1 *rlwe.SecretKey) *rlwe.SecretKey {
	return ConstructExtendedSK(kgen.params.HK, paramsRP, skS, skS1)
}

// ConstructExtendedSK builds the extended secret key s̃ = s + Y·s̃₁ in the
// extension ring R' (degree 2N) from two secret keys at the homing-key level.
//
// paramsHK: the homing-key parameters (Q = Q_eval ∪ P_eval)
// paramsRP: the target R' parameters (degree 2N)
// skS, skS1: secret keys at paramsHK level
func ConstructExtendedSK(paramsHK, paramsRP rlwe.Parameters, skS, skS1 *rlwe.SecretKey) *rlwe.SecretKey {
	N := paramsHK.N()
	ringQHK := paramsHK.RingQ()
	ringQRP := paramsRP.RingQ()

	skTilde := rlwe.NewSecretKey(paramsRP)

	// Convert s and s̃₁ from NTT+Montgomery to coefficient domain.
	// Both are at HK level (Q_eval ∪ P_eval primes).
	sCoeffs := ringQHK.NewPoly()
	s1Coeffs := ringQHK.NewPoly()
	ringQHK.IMForm(skS.Value.Q, sCoeffs)
	ringQHK.INTT(sCoeffs, sCoeffs)
	ringQHK.IMForm(skS1.Value.Q, s1Coeffs)
	ringQHK.INTT(s1Coeffs, s1Coeffs)

	// Interleave into R' (degree 2N): even = s, odd = s̃₁
	// Use min(paramsRP.QCount(), paramsHK.QCount()) primes from HK coefficients
	sTildeCoeffs := ringQRP.NewPoly()
	nQ := paramsRP.QCount()
	if nQ > paramsHK.QCount() {
		nQ = paramsHK.QCount()
	}
	for m := 0; m < nQ; m++ {
		for j := 0; j < N; j++ {
			sTildeCoeffs.Coeffs[m][2*j] = sCoeffs.Coeffs[m][j]
			sTildeCoeffs.Coeffs[m][2*j+1] = s1Coeffs.Coeffs[m][j]
		}
	}

	ringQRP.NTT(sTildeCoeffs, skTilde.Value.Q)
	ringQRP.MForm(skTilde.Value.Q, skTilde.Value.Q)

	// Extend to P basis
	if paramsRP.PCount() > 0 {
		ringQP := paramsRP.RingQP().AtLevel(skTilde.LevelQ(), skTilde.LevelP())
		ringQP.ExtendBasisSmallNormAndCenter(sTildeCoeffs, skTilde.LevelP(), sTildeCoeffs, skTilde.Value.P)
		paramsRP.RingP().NTT(skTilde.Value.P, skTilde.Value.P)
		paramsRP.RingP().MForm(skTilde.Value.P, skTilde.Value.P)
	}

	return skTilde
}
