package kgplus

import (
	"fmt"

	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	"github.com/tuneinsight/lattigo/v6/ring"
)

// TransmissionKeys holds everything the client sends to the server.
// This is the only data that crosses the client-server boundary.
type TransmissionKeys struct {
	// HomingKey switches from s̃₁ to s in R (at HK parameter level).
	HomingKey *rlwe.EvaluationKey

	// MasterRotKeys are GaloisKeys in R' at the top RPrime level,
	// paper convention: each encrypts P_top·G_i·π(s̃) under s̃.
	// Indexed by rotation index (not Galois element).
	MasterRotKeys map[int]*rlwe.GaloisKey

	// Shift0Keys[i] is the identity (shift-0) GaloisKey at RPrime[i].
	// Each encrypts P_i·s̃ under s̃ and serves as the seed for RotToRot.
	// Length is k-1 (one per level except the top).
	Shift0Keys []*rlwe.GaloisKey
}

// KeyGenerator generates transmission keys on the client side.
// It does NOT store the secret key — following lattigo's KeyGenerator pattern.
type KeyGenerator struct {
	params Parameters
	kgenHK *rlwe.KeyGenerator   // at HK parameter level
	kgenRP []*rlwe.KeyGenerator // one per RPrime level
}

// NewKeyGenerator creates a KeyGenerator for the given hierarchical parameters.
func NewKeyGenerator(params Parameters) *KeyGenerator {
	k := params.NumLevels()
	kgenRP := make([]*rlwe.KeyGenerator, k)
	for i := 0; i < k; i++ {
		kgenRP[i] = rlwe.NewKeyGenerator(params.RPrime[i])
	}
	return &KeyGenerator{
		params: params,
		kgenHK: rlwe.NewKeyGenerator(params.HK),
		kgenRP: kgenRP,
	}
}

// GenSecretKeyNew generates a secret key at the homing-key level.
// The returned key has Q = Q_eval ∪ P_eval and P = P_hk.
//
// For evaluation (encryption/decryption), project it to eval level with
// [ProjectToEvalKey].
func (kgen *KeyGenerator) GenSecretKeyNew() *rlwe.SecretKey {
	return kgen.kgenHK.GenSecretKeyNew()
}

// ProjectToEvalKey projects a homing-key-level secret key to evaluation level.
// The evaluation key has Q = Q_eval and P = P_eval.
//
// This copies the first QCount primes to Q and remaps the remaining primes to P.
func (kgen *KeyGenerator) ProjectToEvalKey(skHK *rlwe.SecretKey) *rlwe.SecretKey {
	skEval := rlwe.NewSecretKey(kgen.params.Eval)
	for m := 0; m <= kgen.params.Eval.MaxLevel(); m++ {
		copy(skEval.Value.Q.Coeffs[m], skHK.Value.Q.Coeffs[m])
	}
	for m := 0; m <= kgen.params.Eval.MaxLevelP(); m++ {
		copy(skEval.Value.P.Coeffs[m], skHK.Value.Q.Coeffs[kgen.params.Eval.QCount()+m])
	}
	return skEval
}

// GenTransmissionKeys generates a homing key, shift-0 keys at each RPrime level,
// and master rotation keys at the top RPrime level.
//
// The sk must be generated by [GenSecretKeyNew] (at HK level).
// masterRotations specifies which rotation indices to generate master keys for.
// Use [hierkeys.MasterRotationsForBase] to compute a good set.
//
// The returned TransmissionKeys is sent to the server.
func (kgen *KeyGenerator) GenTransmissionKeys(sk *rlwe.SecretKey, masterRotations []int) (*TransmissionKeys, error) {

	if sk == nil {
		return nil, fmt.Errorf("secret key must not be nil")
	}

	k := kgen.params.NumLevels()

	// Generate s̃₁ (independent secret in R at HK level)
	skS1 := kgen.kgenHK.GenSecretKeyNew()

	// Homing key: switches s̃₁ → s at HK level
	homingKey := kgen.kgenHK.GenEvaluationKeyNew(skS1, sk)

	// Generate shift-0 keys at each RPrime level 0..k-2
	shift0Keys := make([]*rlwe.GaloisKey, k-1)
	for level := 0; level < k-1; level++ {
		skTilde := kgen.constructExtendedSKForParams(kgen.params.RPrime[level], sk, skS1)
		shift0EK := kgen.kgenRP[level].GenEvaluationKeyNew(skTilde, skTilde)
		shift0Keys[level] = &rlwe.GaloisKey{
			EvaluationKey: *shift0EK,
			GaloisElement: 1, // identity
			NthRoot:       kgen.params.RPrime[level].RingQ().NthRoot(),
		}
	}

	// Generate master rotation keys at the top RPrime level (paper convention)
	topLevel := k - 1
	paramsTop := kgen.params.RPrime[topLevel]
	skTildeTop := kgen.constructExtendedSKForParams(paramsTop, sk, skS1)

	masterRotKeys := make(map[int]*rlwe.GaloisKey, len(masterRotations))
	for _, rot := range masterRotations {
		galElRP := paramsTop.GaloisElement(rot)

		// Paper convention: genEvalKey(skIn=π(s̃), skOut=s̃)
		skTildeAut := rlwe.NewSecretKey(paramsTop)
		index, err := ring.AutomorphismNTTIndex(paramsTop.N(), paramsTop.RingQ().NthRoot(), galElRP)
		if err != nil {
			return nil, fmt.Errorf("AutomorphismNTTIndex for rot=%d: %w", rot, err)
		}
		paramsTop.RingQ().AutomorphismNTTWithIndex(skTildeTop.Value.Q, index, skTildeAut.Value.Q)
		paramsTop.RingP().AutomorphismNTTWithIndex(skTildeTop.Value.P, index, skTildeAut.Value.P)

		evk := kgen.kgenRP[topLevel].GenEvaluationKeyNew(skTildeAut, skTildeTop)
		masterRotKeys[rot] = &rlwe.GaloisKey{
			EvaluationKey: *evk,
			GaloisElement: galElRP,
			NthRoot:       paramsTop.RingQ().NthRoot(),
		}
	}

	return &TransmissionKeys{
		HomingKey:     homingKey,
		MasterRotKeys: masterRotKeys,
		Shift0Keys:    shift0Keys,
	}, nil
}

// constructExtendedSKForParams builds s̃ = s + Y·s̃₁ in R' for the given R' parameter set.
func (kgen *KeyGenerator) constructExtendedSKForParams(paramsRP rlwe.Parameters, skS, skS1 *rlwe.SecretKey) *rlwe.SecretKey {
	return ConstructExtendedSK(kgen.params.HK, paramsRP, skS, skS1)
}

// ConstructExtendedSK builds the extended secret key s̃ = s + Y·s̃₁ in the
// extension ring R' (degree 2N) from two secret keys at the homing-key level.
//
// paramsHK: the homing-key parameters (Q = Q_eval ∪ P_eval, P = P_hk)
// paramsRP: the target R' parameters (degree 2N)
// skS, skS1: secret keys at paramsHK level
//
// For k>2, paramsRP.Q may include primes beyond paramsHK.Q (e.g., the HK P primes).
// In that case, the additional coefficient slots are filled from skS.P and skS1.P.
func ConstructExtendedSK(paramsHK, paramsRP rlwe.Parameters, skS, skS1 *rlwe.SecretKey) *rlwe.SecretKey {
	N := paramsHK.N()
	ringQHK := paramsHK.RingQ()
	ringPHK := paramsHK.RingP()
	ringQRP := paramsRP.RingQ()

	skTilde := rlwe.NewSecretKey(paramsRP)

	// Convert s and s̃₁ Q-part from NTT+Montgomery to coefficient domain.
	sCoeffsQ := ringQHK.NewPoly()
	s1CoeffsQ := ringQHK.NewPoly()
	ringQHK.IMForm(skS.Value.Q, sCoeffsQ)
	ringQHK.INTT(sCoeffsQ, sCoeffsQ)
	ringQHK.IMForm(skS1.Value.Q, s1CoeffsQ)
	ringQHK.INTT(s1CoeffsQ, s1CoeffsQ)

	// Interleave into R' (degree 2N): even = s, odd = s̃₁
	sTildeCoeffs := ringQRP.NewPoly()

	// Fill from HK Q primes
	nQFromQ := paramsRP.QCount()
	if nQFromQ > paramsHK.QCount() {
		nQFromQ = paramsHK.QCount()
	}
	for m := 0; m < nQFromQ; m++ {
		for j := 0; j < N; j++ {
			sTildeCoeffs.Coeffs[m][2*j] = sCoeffsQ.Coeffs[m][j]
			sTildeCoeffs.Coeffs[m][2*j+1] = s1CoeffsQ.Coeffs[m][j]
		}
	}

	// Fill additional Q primes from HK P primes (for k>2 where RPrime.Q > HK.Q)
	if paramsRP.QCount() > paramsHK.QCount() && ringPHK != nil {
		sCoeffsP := ringPHK.NewPoly()
		s1CoeffsP := ringPHK.NewPoly()
		ringPHK.IMForm(skS.Value.P, sCoeffsP)
		ringPHK.INTT(sCoeffsP, sCoeffsP)
		ringPHK.IMForm(skS1.Value.P, s1CoeffsP)
		ringPHK.INTT(s1CoeffsP, s1CoeffsP)

		nExtra := paramsRP.QCount() - paramsHK.QCount()
		if nExtra > paramsHK.PCount() {
			nExtra = paramsHK.PCount()
		}
		for m := 0; m < nExtra; m++ {
			rpIdx := paramsHK.QCount() + m
			for j := 0; j < N; j++ {
				sTildeCoeffs.Coeffs[rpIdx][2*j] = sCoeffsP.Coeffs[m][j]
				sTildeCoeffs.Coeffs[rpIdx][2*j+1] = s1CoeffsP.Coeffs[m][j]
			}
		}
	}

	ringQRP.NTT(sTildeCoeffs, skTilde.Value.Q)
	ringQRP.MForm(skTilde.Value.Q, skTilde.Value.Q)

	// Extend to P basis
	if paramsRP.PCount() > 0 {
		ringQP := paramsRP.RingQP().AtLevel(skTilde.LevelQ(), skTilde.LevelP())
		ringQP.ExtendBasisSmallNormAndCenter(sTildeCoeffs, skTilde.LevelP(), sTildeCoeffs, skTilde.Value.P)
		paramsRP.RingP().NTT(skTilde.Value.P, skTilde.Value.P)
		paramsRP.RingP().MForm(skTilde.Value.P, skTilde.Value.P)
	}

	return skTilde
}
