package llkn

import (
	"fmt"

	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	"github.com/tuneinsight/lattigo/v6/ring"
)

// TransmissionKeys holds everything the client sends to the server.
type TransmissionKeys struct {
	// MasterRotKeys are GaloisKeys at Master level (degree N),
	// paper convention: each encrypts P_master·G_i·σ_r(s) under s.
	// Indexed by rotation index (not Galois element).
	MasterRotKeys map[int]*rlwe.GaloisKey

	// Shift0Key is the identity (shift-0) GaloisKey at Eval level (degree N).
	// It encrypts P_eval·s under s and serves as the seed for RotToRot.
	//
	// In the full LLKN scheme this would be derived server-side via PubToRot.
	// We send it directly for simplicity; PubToRot can be added as a future
	// bandwidth optimization.
	Shift0Key *rlwe.GaloisKey
}

// KeyGenerator generates transmission keys on the client side.
type KeyGenerator struct {
	params     Parameters
	kgenEval   *rlwe.KeyGenerator // at eval parameter level
	kgenMaster *rlwe.KeyGenerator // at master parameter level
}

// NewKeyGenerator creates a KeyGenerator for the given LLKN parameters.
func NewKeyGenerator(params Parameters) *KeyGenerator {
	return &KeyGenerator{
		params:     params,
		kgenEval:   rlwe.NewKeyGenerator(params.Eval),
		kgenMaster: rlwe.NewKeyGenerator(params.Master),
	}
}

// GenSecretKeyNew generates a secret key at the master level.
// The returned key has Q = Q_eval ∪ P_eval and P = P_master.
//
// For evaluation (encryption/decryption), project it to eval level with
// [ProjectToEvalKey].
func (kgen *KeyGenerator) GenSecretKeyNew() *rlwe.SecretKey {
	return kgen.kgenMaster.GenSecretKeyNew()
}

// ProjectToEvalKey projects a master-level secret key to evaluation level.
// The evaluation key has Q = Q_eval and P = P_eval.
func (kgen *KeyGenerator) ProjectToEvalKey(skMaster *rlwe.SecretKey) *rlwe.SecretKey {
	skEval := rlwe.NewSecretKey(kgen.params.Eval)
	for m := 0; m <= kgen.params.Eval.MaxLevel(); m++ {
		copy(skEval.Value.Q.Coeffs[m], skMaster.Value.Q.Coeffs[m])
	}
	for m := 0; m <= kgen.params.Eval.MaxLevelP(); m++ {
		copy(skEval.Value.P.Coeffs[m], skMaster.Value.Q.Coeffs[kgen.params.Eval.QCount()+m])
	}
	return skEval
}

// GenTransmissionKeys generates a shift-0 key and master rotation keys.
//
// The sk must be generated by [GenSecretKeyNew] (at master level).
// masterRotations specifies which rotation indices to generate master keys for.
// Use [hierkeys.MasterRotationsForBase] to compute a good set.
//
// The returned TransmissionKeys is sent to the server.
func (kgen *KeyGenerator) GenTransmissionKeys(sk *rlwe.SecretKey, masterRotations []int) (*TransmissionKeys, error) {

	if sk == nil {
		return nil, fmt.Errorf("secret key must not be nil")
	}

	// Project sk to eval level for shift-0 key generation
	skEval := kgen.ProjectToEvalKey(sk)

	// Generate shift-0 key at eval level: identity key-switch key Enc_s(P_eval·s)
	shift0EK := kgen.kgenEval.GenEvaluationKeyNew(skEval, skEval)
	shift0Key := &rlwe.GaloisKey{
		EvaluationKey: *shift0EK,
		GaloisElement: 1, // identity
		NthRoot:       kgen.params.Eval.RingQ().NthRoot(),
	}

	// Generate master rotation keys at master level (paper convention)
	masterRotKeys := make(map[int]*rlwe.GaloisKey, len(masterRotations))
	for _, rot := range masterRotations {
		galEl := kgen.params.Master.GaloisElement(rot)

		// Paper convention: genEvalKey(skIn=σ_r(s), skOut=s)
		skAut := rlwe.NewSecretKey(kgen.params.Master)
		index, err := ring.AutomorphismNTTIndex(kgen.params.Master.N(), kgen.params.Master.RingQ().NthRoot(), galEl)
		if err != nil {
			return nil, fmt.Errorf("AutomorphismNTTIndex for rot=%d: %w", rot, err)
		}
		kgen.params.Master.RingQ().AutomorphismNTTWithIndex(sk.Value.Q, index, skAut.Value.Q)
		kgen.params.Master.RingP().AutomorphismNTTWithIndex(sk.Value.P, index, skAut.Value.P)

		evk := kgen.kgenMaster.GenEvaluationKeyNew(skAut, sk)
		masterRotKeys[rot] = &rlwe.GaloisKey{
			EvaluationKey: *evk,
			GaloisElement: galEl,
			NthRoot:       kgen.params.Master.RingQ().NthRoot(),
		}
	}

	return &TransmissionKeys{
		MasterRotKeys: masterRotKeys,
		Shift0Key:     shift0Key,
	}, nil
}
