package llkn

import (
	"fmt"

	hierkeys "github.com/butvinm/lattigo-hierkeys"
	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	"github.com/tuneinsight/lattigo/v6/ring"
)

// TransmissionKeys holds everything the client sends to the server.
type TransmissionKeys struct {
	// MasterRotKeys are rotation keys at the top level (Levels[k-1]) in paper
	// convention. Indexed by rotation index (not Galois element).
	MasterRotKeys map[int]*hierkeys.MasterKey

	// EncZero is an encryption of zero at the top level (Levels[k-1]).
	// The server derives shift-0 keys at each lower level via PubToRot.
	EncZero *rlwe.Ciphertext
}

// KeyGenerator generates transmission keys on the client side.
type KeyGenerator struct {
	params Parameters
	kgens  []*rlwe.KeyGenerator // one per level
}

// NewKeyGenerator creates a KeyGenerator for the given LLKN parameters.
func NewKeyGenerator(params Parameters) *KeyGenerator {
	k := params.NumLevels()
	kgens := make([]*rlwe.KeyGenerator, k)
	for i := 0; i < k; i++ {
		kgens[i] = rlwe.NewKeyGenerator(params.Levels[i])
	}
	return &KeyGenerator{
		params: params,
		kgens:  kgens,
	}
}

// GenSecretKeyNew generates a secret key at the top level.
// The returned key has Q = Levels[k-1].Q and P = Levels[k-1].P.
//
// For evaluation (encryption/decryption), project it to eval level with
// [ProjectToEvalKey].
func (kgen *KeyGenerator) GenSecretKeyNew() *rlwe.SecretKey {
	return kgen.kgens[len(kgen.kgens)-1].GenSecretKeyNew()
}

// ProjectToEvalKey projects a top-level secret key to evaluation level.
// The evaluation key has Q = Q_eval and P = P_eval.
//
// Returns an error if the secret key is not at the expected top level.
func (kgen *KeyGenerator) ProjectToEvalKey(skTop *rlwe.SecretKey) (*rlwe.SecretKey, error) {
	expectedQ := kgen.params.Top().QCount()
	if skTop.LevelQ()+1 != expectedQ {
		return nil, fmt.Errorf("sk has %d Q primes, want %d (top level)", skTop.LevelQ()+1, expectedQ)
	}
	return kgen.projectToLevel(skTop, 0), nil
}

// projectToLevel projects a top-level secret key to the given level.
// Level i has Q = first Levels[i].QCount() primes and P = next Levels[i].PCount() primes
// from the top-level Q.
func (kgen *KeyGenerator) projectToLevel(skTop *rlwe.SecretKey, level int) *rlwe.SecretKey {
	paramsLevel := kgen.params.Levels[level]
	skLevel := rlwe.NewSecretKey(paramsLevel)
	for m := 0; m <= paramsLevel.MaxLevel(); m++ {
		copy(skLevel.Value.Q.Coeffs[m], skTop.Value.Q.Coeffs[m])
	}
	for m := 0; m <= paramsLevel.MaxLevelP(); m++ {
		copy(skLevel.Value.P.Coeffs[m], skTop.Value.Q.Coeffs[paramsLevel.QCount()+m])
	}
	return skLevel
}

// GenTransmissionKeys generates shift-0 keys at each level and master
// rotation keys at the top level.
//
// The sk must be generated by [GenSecretKeyNew] (at top level).
// masterRotations specifies which rotation indices to generate master keys for.
// Use [hierkeys.MasterRotationsForBase] to compute a good set.
//
// The returned TransmissionKeys is sent to the server.
func (kgen *KeyGenerator) GenTransmissionKeys(sk *rlwe.SecretKey, masterRotations []int) (*TransmissionKeys, error) {

	if sk == nil {
		return nil, fmt.Errorf("secret key must not be nil")
	}

	k := kgen.params.NumLevels()

	// Generate encryption of zero at the top level.
	// The server will derive shift-0 keys at each lower level via PubToRot.
	topLevel := k - 1
	paramsTop := kgen.params.Levels[topLevel]
	encZero := rlwe.NewCiphertext(paramsTop, 1, paramsTop.MaxLevel())
	encZero.IsNTT = true
	encZero.IsMontgomery = true
	enc := rlwe.NewEncryptor(paramsTop, sk)
	var err error
	if err = enc.EncryptZero(encZero); err != nil {
		return nil, fmt.Errorf("encrypt zero: %w", err)
	}

	// Generate master rotation keys at top level (paper convention)
	masterRotKeys := make(map[int]*hierkeys.MasterKey, len(masterRotations))
	for _, rot := range masterRotations {
		galEl := paramsTop.GaloisElement(rot)

		// Paper convention: genEvalKey(skIn=σ_r(s), skOut=s)
		skAut := rlwe.NewSecretKey(paramsTop)
		index, err := ring.AutomorphismNTTIndex(paramsTop.N(), paramsTop.RingQ().NthRoot(), galEl)
		if err != nil {
			return nil, fmt.Errorf("AutomorphismNTTIndex for rot=%d: %w", rot, err)
		}
		paramsTop.RingQ().AutomorphismNTTWithIndex(sk.Value.Q, index, skAut.Value.Q)
		paramsTop.RingP().AutomorphismNTTWithIndex(sk.Value.P, index, skAut.Value.P)

		evk := kgen.kgens[topLevel].GenEvaluationKeyNew(skAut, sk)
		masterRotKeys[rot] = hierkeys.NewMasterKey(&rlwe.GaloisKey{
			EvaluationKey: *evk,
			GaloisElement: galEl,
			NthRoot:       paramsTop.RingQ().NthRoot(),
		})
	}

	return &TransmissionKeys{
		MasterRotKeys: masterRotKeys,
		EncZero:       encZero,
	}, nil
}
